package com.example.service

import android.app.Notification
import android.content.ComponentName
import android.content.Context
import android.content.Intent
import android.os.Build
import android.provider.Settings
import android.service.notification.NotificationListenerService
import android.service.notification.StatusBarNotification
import android.text.TextUtils
import android.util.Log
import com.example.NotifyClipApplication
import com.example.data.local.entity.NotificationEntity
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.launch

/**
 * Production-ready Android NotificationListenerService implementation.
 * Intercepts incoming notifications posted by applications and persists them
 * into the local Room database via NotificationRepository.
 */
class AppNotificationListenerService : NotificationListenerService() {

    private val serviceScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    override fun onNotificationPosted(sbn: StatusBarNotification?) {
        super.onNotificationPosted(sbn)
        if (sbn == null) return

        try {
            val packageName = sbn.packageName ?: "unknown"

            // Skip notifications generated by our own app to avoid circular loops
            if (packageName == applicationContext.packageName) return

            val notification = sbn.notification ?: return
            val extras = notification.extras ?: return

            // Extract title
            val title = extras.getCharSequence(Notification.EXTRA_TITLE)?.toString()
                ?: extras.getCharSequence(Notification.EXTRA_TITLE_BIG)?.toString()
                ?: ""

            // Extract body text (prefer big text if expanded, then regular text or sub text)
            val body = extras.getCharSequence(Notification.EXTRA_BIG_TEXT)?.toString()
                ?: extras.getCharSequence(Notification.EXTRA_TEXT)?.toString()
                ?: extras.getCharSequence(Notification.EXTRA_SUB_TEXT)?.toString()
                ?: ""

            // Skip empty/silent utility notifications if they contain neither title nor body
            if (title.isBlank() && body.isBlank()) return

            // Resolve readable application label
            val pm = applicationContext.packageManager
            val appName = try {
                val appInfo = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                    pm.getApplicationInfo(packageName, 0)
                } else {
                    @Suppress("DEPRECATION")
                    pm.getApplicationInfo(packageName, 0)
                }
                pm.getApplicationLabel(appInfo).toString()
            } catch (e: Exception) {
                packageName.substringAfterLast('.').replaceFirstChar { it.uppercase() }
            }

            val timestamp = if (sbn.postTime > 0) sbn.postTime else System.currentTimeMillis()

            val notificationEntity = NotificationEntity(
                appName = appName,
                packageName = packageName,
                title = title.ifBlank { "Notification" },
                body = body.ifBlank { "(No content)" },
                timestamp = timestamp
            )

            serviceScope.launch {
                try {
                    NotifyClipApplication.instance.notificationRepository.insert(notificationEntity)
                    Log.d(TAG, "Saved notification from $appName: $title")
                } catch (e: Exception) {
                    Log.e(TAG, "Error persisting notification", e)
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to process posted notification", e)
        }
    }

    override fun onNotificationRemoved(sbn: StatusBarNotification?) {
        super.onNotificationRemoved(sbn)
        // Kept in persistent history; remove is not needed here
    }

    companion object {
        private const val TAG = "NotificationListener"

        /**
         * Checks whether the user has enabled Notification Listener access for this app in Android system settings.
         */
        fun isNotificationAccessGranted(context: Context): Boolean {
            val pkgName = context.packageName
            val flat = Settings.Secure.getString(
                context.contentResolver,
                "enabled_notification_listeners"
            )
            if (!TextUtils.isEmpty(flat)) {
                val names = flat.split(":".toRegex()).toTypedArray()
                for (name in names) {
                    val component = ComponentName.unflattenFromString(name)
                    if (component != null && TextUtils.equals(pkgName, component.packageName)) {
                        return true
                    }
                }
            }
            return false
        }

        /**
         * Opens the system settings screen where the user can grant Notification Listener access.
         */
        fun openNotificationAccessSettings(context: Context) {
            try {
                val intent = Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS).apply {
                    flags = Intent.FLAG_ACTIVITY_NEW_TASK
                }
                context.startActivity(intent)
            } catch (e: Exception) {
                Log.e(TAG, "Could not open notification listener settings", e)
            }
        }
    }
}
